<a href="https://www.kaggle.com/code/philiprybkin/kagglehw?scriptVersionId=352781139" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

Імпорт модулів

In [1]:
import torch

# Завдання 1

Перегляньте інформацію про доступні процесори, та виведіть про них інформацію

In [2]:
print(torch.cuda.is_available())  # True/False

if torch.cuda.is_available():
    print(torch.cuda.device_count())  # Кількість GPU
    print(torch.cuda.get_device_name(0))  # Назва першого GPU

tensor = torch.tensor([1, 2, 3])
print(tensor.device)  # CPU

True
2
Tesla T4
cpu


# Завдання 2
Підключіться до процесора GPU, та знову виведіть інформацію про доступні процесори

In [3]:
tensor_gpu = tensor.to("cuda")


tensor_gpu

tensor([1, 2, 3], device='cuda:0')

# Завдання 3
Створіть випадковий тензор розміру (2, 3). Виведіть інформацію про його:

* розмір
* тип даних
* процесор
* наявність градієнта

In [4]:
import torch
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
tensor_a = torch.from_numpy(a)

print(a, '\n')

print(tensor_a, '\n')

print(f'{tensor_a.shape=}\n')

print(f'{tensor_a.size()=}')

[[1 2 3]
 [4 5 6]] 

tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor_a.shape=torch.Size([2, 3])

tensor_a.size()=torch.Size([2, 3])


# Завдання 4

Створіть 2 тензора розміру 100. Виведіть
* суму векторів
* частку векторів(перед цим замініть один елемент на 0)
* максимальне та мінімальне значення(методи .min() .max())
* середнє значення(метод .mean())
* квадрад різниці
* середнє значення квадрату різниці

In [5]:
import torch

# 1. Створюємо 2 тензори розміру 100
tensor1 = torch.randn(100)
tensor2 = torch.randn(100)

# 2. Сума векторів
sum_vectors = tensor1 + tensor2
print("Сума векторів:")
print(sum_vectors)

# 3. Замінюємо один елемент на 0
tensor2[0] = 0

# Частка векторів
division_vectors = tensor1 / tensor2
print("\nЧастка векторів:")
print(division_vectors)

# 4. Максимальне та мінімальне значення
print("\nМінімальне значення tensor1:", tensor1.min())
print("Максимальне значення tensor1:", tensor1.max())

print("Мінімальне значення tensor2:", tensor2.min())
print("Максимальне значення tensor2:", tensor2.max())

# 5. Середнє значення
print("\nСереднє значення tensor1:", tensor1.mean())
print("Середнє значення tensor2:", tensor2.mean())

# 6. Квадрат різниці
squared_difference = (tensor1 - tensor2) ** 2
print("\nКвадрат різниці:")
print(squared_difference)

# 7. Середнє значення квадрату різниці
mean_squared_difference = squared_difference.mean()
print("\nСереднє значення квадрату різниці:")
print(mean_squared_difference)

Сума векторів:
tensor([ 2.4321e-03, -1.6808e+00, -7.5228e-01,  8.1395e-01,  1.8772e+00,
        -8.3906e-02,  1.2105e+00,  2.5283e+00,  1.8786e+00,  6.8027e-01,
         1.3610e+00,  6.2119e-01,  1.1935e+00, -5.8761e-01, -1.6607e+00,
        -1.4876e+00, -8.0067e-01,  7.8416e-01,  1.0678e+00, -3.1835e-02,
         1.0929e+00,  1.4327e+00,  1.0884e+00,  3.9361e-01, -1.4811e+00,
        -1.4204e+00, -1.2552e+00, -1.0235e+00, -5.0806e-02, -1.8746e+00,
         6.7102e-02,  1.2326e+00,  3.5753e-01, -3.2550e+00,  5.8309e-01,
         1.9061e+00,  1.2903e+00,  2.5907e+00,  1.0755e-01,  1.3280e+00,
        -1.6372e+00,  1.3464e+00, -1.6635e+00,  2.8407e-01,  2.0583e-01,
         1.5597e+00, -1.5846e+00,  1.4722e+00, -3.9321e-01, -2.2135e+00,
         2.6014e+00, -2.3197e+00, -8.7209e-02, -1.6645e+00,  9.0811e-01,
         6.4335e-01,  4.2184e-01,  1.5991e+00, -1.0491e+00,  4.0882e-02,
         7.6722e-01,  1.4762e+00, -1.6251e+00,  5.2504e-01,  2.1658e+00,
        -1.1034e+00,  4.7051e-01, -1

# Завдання 5

У вашому розпорядженні є нейронна мережа, яка прогнозує **орієнтовну ціну квартири** на основі двох **ознак**:

* **площі квартири** (у квадратних метрах);
* **кількості кімнат**.

Вам надано готовий клас `NeuralNetwork` із методом `predict`.

1. Створіть екземпляр класу `NeuralNetwork`, передайте як параметр `device`.
2. За допомогою методу `predict()` визначте прогнозовану ціну квартири, яка:
   * має площу **65 м²**;
   * має **2 кімнати**.
     
3. Для цього створіть тензор із відповідними числами та скористайтесь методом `predict()`.
4. Усі нейромережі очікують дані розміру `(N, K)`, де:
   * `N` — кількість об'єктів, для яких виконується прогноз;
   * `K` — кількість ознак. У цьому випадку їх дві — **площа квартири та кількість кімнат**.

5. Спробуйте скористатись методом `predict()` разом із `torch.no_grad()`:

```python
with torch.no_grad():
    price = model.predict(...)
```

**Завдання:** отримайте прогнозовану ціну квартири та виведіть результат на екран.


In [8]:
import torch


class NeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [[3.3, -38.]],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [176.],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 2:
            raise ValueError(
                f"Очікується 2 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою (float32 або float64)."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        return X @ self.W.T + self.b


In [9]:
import torch

# device вже має бути визначений у вашому завданні
# наприклад:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Створюємо модель
model = NeuralNetwork(device=device)

# Створюємо тензор:
# 65 м² — площа
# 2 — кількість кімнат
# shape = (1, 2), тобто 1 квартира та 2 ознаки
x = torch.tensor([[65.0, 2.0]], device=device)

# Робимо прогноз без обчислення градієнтів
with torch.no_grad():
    price = model.predict(x)

print("Прогнозована ціна квартири:", price)

Прогнозована ціна квартири: tensor([[314.5000]], device='cuda:0')


# **Завдання 6**

У таблиці наведено інформацію про три квартири.

| **Квартира** | **Площа (м²)** | **Кількість кімнат** |
| ------------ | -------------: | -------------------: |
| Квартира 1   |             40 |                    1 |
| Квартира 2   |             60 |                    3 |
| Квартира 3   |             100 |                    2 |

Виконайте наступні кроки:

1. Створіть **три окремі тензори** (`X1`, `X2`, `X3`), кожен з яких містить дані про одну квартиру.
2. За допомогою методу `predict()` обчисліть **прогнозовану ціну** для кожної квартири окремо.
3. Створіть **один тензор** `X` розміру **(3, 2)**, де:
   * кожен рядок відповідає одній квартирі;
   * перший стовпець — площа квартири;
   * другий стовпець — кількість кімнат.

4. За допомогою одного виклику `predict(X)` отримайте **прогнозовану ціну одразу для всіх трьох квартир**.
5. Виведіть розмір тензору з трьома прогнозованими цінами, який ви отримали на кроці 4.
6. Порівняйте результати, отримані окремими викликами `predict()` та одним спільним викликом `predict(X)`.


In [10]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = NeuralNetwork(device=device)

# 1. Три окремі тензори
X1 = torch.tensor([[40.0, 1.0]], device=device)
X2 = torch.tensor([[60.0, 3.0]], device=device)
X3 = torch.tensor([[100.0, 2.0]], device=device)

# 2. Прогноз для кожної квартири окремо
with torch.no_grad():
    price1 = model.predict(X1)
    price2 = model.predict(X2)
    price3 = model.predict(X3)

print("Квартира 1:", price1)
print("Квартира 2:", price2)
print("Квартира 3:", price3)

# 3. Один тензор для всіх трьох квартир
X = torch.tensor([
    [40.0, 1.0],
    [60.0, 3.0],
    [100.0, 2.0]
], device=device)

# 4. Один спільний виклик predict()
with torch.no_grad():
    prices = model.predict(X)

print("\nПрогнози для всіх квартир:", prices)

# 5. Розмір тензора з прогнозами
print("Розмір тензора:", prices.shape)

# 6. Порівняння
print("\nПорівняння:")
print("Окремо:", price1, price2, price3)
print("Разом:  ", prices)

Квартира 1: tensor([[270.]], device='cuda:0')
Квартира 2: tensor([[260.]], device='cuda:0')
Квартира 3: tensor([[430.]], device='cuda:0')

Прогнози для всіх квартир: tensor([[270.],
        [260.],
        [430.]], device='cuda:0')
Розмір тензора: torch.Size([3, 1])

Порівняння:
Окремо: tensor([[270.]], device='cuda:0') tensor([[260.]], device='cuda:0') tensor([[430.]], device='cuda:0')
Разом:   tensor([[270.],
        [260.],
        [430.]], device='cuda:0')


# Завдання 7

Три квартири були продані, і стали відомі їхні **реальні ціни**.

| Квартира   | Реальна ціна (1000$) |
| ---------- | ---------------: |
| Квартира 1 |           210 |
| Квартира 2 |          310 |
| Квартира 3 |          360 |

Нехай прогноз моделі збережений у змінній `y_pred`, а реальні значення — у `y_true`.

Визначте, **наскільки модель помилилася**, використавши два різних підходи.

### Варіант 1

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Обчисліть середнє значення цієї різниці за допомогою `torch.mean()`.

### Варіант 2

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Позбудьтеся від'ємних значень за допомогою `torch.abs()`.
3. Обчисліть середнє значення отриманих помилок.

### Запитання

1. Який із двох варіантів краще характеризує якість моделі? Поясніть свою відповідь.
2. Напишіть функцію `loss_fn()`, яка реалізує обраний варіант.

```python
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    ...
```




In [11]:
# Я думаю, що варіант 2 кращий, тому що ми використовуємо torch.abs() і всі помилки стають додатними.
# Наприклад, якщо модель помилилася на -20 і на 20, то при першому способі вони можуть взаємно компенсуватися

import torch

y_pred = prices

y_true = torch.tensor(
    [210.0, 310.0, 360.0],
    device=device
)

# Варіант 1
difference = y_pred - y_true
loss1 = torch.mean(difference)

print("Помилка 1:", loss1)

# Варіант 2
difference = y_pred - y_true
difference = torch.abs(difference)
loss2 = torch.mean(difference)

print("Помилка 2:", loss2)

def loss_fn(y_pred, y_true):
    difference = y_pred - y_true
    difference = torch.abs(difference)
    return torch.mean(difference)


loss = loss_fn(y_pred, y_true)

print("MAE:", loss)



Помилка 1: tensor(26.6667, device='cuda:0')
Помилка 2: tensor(88.8889, device='cuda:0')
MAE: tensor(88.8889, device='cuda:0')


# Завдання 8

У вашому розпорядженні є вчитель, який може навчити нейронну мережу робити точніші прогнози **цін на квартири**.

Клас `Teacher` вже реалізований. Під час створення об'єкта необхідно передати модель, яку потрібно навчати:

```python
teacher = Teacher(model)
```

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Виведіть тензор `X`, який містить дані про квартири:
   * площу квартири;
   * кількість кімнат.

3. Виведіть тензор `y_true` з **реальними цінами квартир**.
4. Отримайте прогноз моделі `y_pred`.
5. Виведіть прогнозовані ціни квартир.
6. За допомогою власної функції `loss_fn()` обчисліть помилку моделі.
7. Виведіть значення помилки.
8. Скористайтеся методом `teach()` класу `Teacher`, передавши йому обчислену помилку.
9. Після навчання знову отримайте прогноз `y_pred`.
10. Виведіть нові прогнозовані ціни квартир.
11. Знову обчисліть та виведіть помилку.
12. Зробіть висновок: **чи стала модель прогнозувати ціни квартир точніше після одного кроку навчання?**



In [12]:
import torch


class Teacher:
    def __init__(self, model, lr=0.02):
        """
        Створює вчителя для навчання моделі.

        Параметри:
            model (NeuralNetwork): модель, яку потрібно навчати.
            lr (float): швидкість навчання.
        """
        self.model = model

        self.optimizer = torch.optim.SGD(
            [model.W, model.b],
            lr=lr
        )

    def teach(self, loss):
        """
        Виконує один крок навчання.

        Параметри:
            loss (torch.Tensor): значення функції втрат.
        """
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()


In [13]:
# Створюємо вчителя
teacher = Teacher(model)

# Дані про квартири
print("X:")
print(X)

# Реальні ціни
y_true = torch.tensor(
    [210.0, 310.0, 360.0],
    device=device
)

print("y_true:")
print(y_true)

# Прогноз моделі до навчання
with torch.no_grad():
    y_pred = model.predict(X)

print("Прогноз до навчання:")
print(y_pred)

# Помилка до навчання
loss = loss_fn(y_pred, y_true)

print("Помилка до навчання:")
print(loss)

# Навчання моделі
# Для навчання градієнт повинен обчислюватися,
# тому тут НЕ використовуємо torch.no_grad()
y_pred = model.predict(X)
loss = loss_fn(y_pred, y_true)

teacher.teach(loss)

# Новий прогноз після навчання
with torch.no_grad():
    y_pred = model.predict(X)

print("Прогноз після навчання:")
print(y_pred)

# Нова помилка
loss = loss_fn(y_pred, y_true)

print("Помилка після навчання:")
print(loss)

X:
tensor([[ 40.,   1.],
        [ 60.,   3.],
        [100.,   2.]], device='cuda:0')
y_true:
tensor([210., 310., 360.], device='cuda:0')
Прогноз до навчання:
tensor([[270.],
        [260.],
        [430.]], device='cuda:0')
Помилка до навчання:
tensor(88.8889, device='cuda:0')
Прогноз після навчання:
tensor([[252.2155],
        [233.3178],
        [385.5444]], device='cuda:0')
Помилка після навчання:
tensor(79.0111, device='cuda:0')


# Завдання 9

Одного кроку навчання недостатньо, щоб модель навчилася добре прогнозувати ціни. Тому повторіть процес навчання **100 разів**.

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить дані про квартири.
3. Створіть тензор `y_true`, який містить реальні реальні ціни.
4. Створіть цикл, який виконається **100 разів**.
5. На кожній ітерації циклу:
   * отримайте прогноз моделі `y_pred`;
   * обчисліть помилку за допомогою функції `loss_fn()`;
   * виведіть помилку на екран;
   * передайте помилку в метод `teacher.teach()`, щоб виконати один крок навчання.
    
6. Після завершення циклу ще раз отримайте прогноз моделі.
7. Виведіть:
   * прогнозовані заробітні плати;
   * значення функції втрат.
    
8. Порівняйте отримані прогнози з реальними ціни. Зробіть висновок, чи покращилася точність моделі після 100 кроків навчання.
9. Cпробуйте зменшити навчальний крок в `teacher`

In [21]:
model = NeuralNetwork(device)
teacher = Teacher(model, lr=0.01)

for i in range(100):
    y_pred = model.predict(X)
    loss = loss_fn(y_pred, y_true)

    teacher.teach(loss)

    if i % 10 == 0:
        print(i, loss.item())

with torch.no_grad():
    y_pred = model.predict(X)

print("Predictions:", y_pred)
print("Real prices:", y_true)
print("Final loss:", loss_fn(y_pred, y_true))

0 88.8888931274414
10 73.33036804199219
20 73.3241958618164
30 73.3180160522461
40 73.31183624267578
50 73.30564880371094
60 73.29947662353516
70 73.29329681396484
80 73.28711700439453
90 73.28092956542969
Predictions: tensor([[240.0937],
        [215.4051],
        [354.9716]], device='cuda:0')
Real prices: tensor([210., 310., 360.], device='cuda:0')
Final loss: tensor(73.2748, device='cuda:0')


In [20]:
teacher = Teacher(model, lr=0.1)

for i in range(100):
    y_pred = model.predict(X)
    loss = loss_fn(y_pred, y_true)

    teacher.teach(loss)

    if i % 10 == 0:
        print(i, loss.item())

with torch.no_grad():
    y_pred = model.predict(X)

print("Predictions:", y_pred)
print("Real prices:", y_true)
print("Final loss:", loss_fn(y_pred, y_true))

0 280.0809020996094
10 280.0809020996094
20 280.0809020996094
30 280.0809020996094
40 280.0809020996094
50 280.0809020996094
60 280.0809020996094
70 280.0809020996094
80 280.0809020996094
90 280.0809020996094
Predictions: tensor([[422.0471],
        [493.2999],
        [804.8958]], device='cuda:0')
Real prices: tensor([210., 310., 360.], device='cuda:0')
Final loss: tensor(280.0809, device='cuda:0')


# Завдання 10

У вашому розпорядженні є нейронна мережа, яка прогнозує **ймовірність дощу**.

Модель використовує три ознаки:

* температура повітря (°C);
* вологість повітря (%);
* швидкість вітру (км/год).

Результатом роботи моделі є **два числа**:

1. ймовірність того, що **дощу не буде**;
2. ймовірність того, що **дощ буде**.

Скористайтеся методом `predict()`, щоб визначити ймовірності для таких погодних умов:

* температура — **20°C**;
* вологість — **80%**;
* швидкість вітру — **15 км/год**.



In [ ]:
import torch


class RainNeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [
                [0.03, 0.01, 0.02],
                [0.06, -0.01, 0.08]
            ],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [-0.2, -0.3],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 3:
            raise ValueError(
                f"Очікується 3 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        logits = X @ self.W.T + self.b
        return torch.softmax(logits, dim=1)

# Завдання 11

Метеостанція надала прогноз погоди на **4 дні**.

| День | Температура (°C) | Вологість (%) | Швидкість вітру (км/год) |
| ---- | ---------------: | ------------: | -----------------------: |
| 1    |               30 |            40 |                        5 |
| 2    |               22 |            85 |                       18 |
| 3    |               15 |            95 |                       25 |
| 4    |               28 |            60 |                       10 |

Виконайте наступні кроки:

1. Створіть один тензор `X` розміру **(4, 3)**, де кожен рядок містить дані про один день.

2. За допомогою методу `predict()` отримайте ймовірності для кожного дня `y_pred`.

3. Скористайтеся функцією `torch.argmax(..., dim=1)`, щоб визначити прогноз моделі `result`:

   * `0` — дощу не буде;
   * `1` — дощ буде.

4. Виведіть:

   * тензор із ймовірностями `y_pred`;
   * тензор із прогнозами `result`


# Завдання 12

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
| ---- | :-: |
| 1    |  Ні |
| 2    | Так |
| 3    | Так |
| 4    |  Ні |

Для навчання моделі використайте готову функцію втрат **CrossEntropyLoss** з бібліотеки **PyTorch**.

### Завдання

1. Створіть об'єкт функції втрат:

   ```python
   loss_fn = torch.nn.CrossEntropyLoss()
   ```

2. Створіть об'єкт класу `Teacher`, передавши йому модель.

3. Створіть тензор `X`, який містить погодні умови за всі 4 дні.

4. Створіть тензор `y_true`, який містить правильні відповіді:

   * `0` — дощу не було;
   * `1` — дощ був.

5. Створіть цикл, який виконається **100 разів**.

6. На кожній ітерації циклу:

   * отримайте ймовірності від моделі `y_pred`:
   * обчисліть помилку:
   * виведіть помилку
   * передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

7. Після завершення циклу ще раз отримайте прогноз моделі.

8. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:

   * `0` — дощу не буде;
   * `1` — дощ буде.

9. Виведіть:

   * ймовірності, отримані від моделі;
   * прогнози моделі (`0` або `1`);
   * правильні відповіді
   * значення функції втра


# Завдання 13

Попробуйте натренувати модель використовуючи функцію втрат, яку ви раніше застосовували для задачі визначення цін на квартири (`torch.nn.MSELoss()`), замість `CrossEntropyLoss`.

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
|------|-----|
| 1    | Ні  |
| 2    | Так |
| 3    | Так |
| 4    | Ні  |

**Завдання**

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить погодні умови за всі 4 дні.
3. Створіть тензор `y_true` розміром (4, 2), де кожен рядок містить інформацію про те чи йшов дощ в цей день:
   - `[1, 0]` — дощу не було
   - `[0, 1]` — дощ був
   -  формат інший тому що ваша функція вимагає щоб `y_true` та `y_pred` були однакового розміру
4. Створіть цикл, який виконається 100 разів.

На кожній ітерації циклу:
- отримайте ймовірності від моделі `y_pred`;
- обчисліть помилку;
- виведіть помилку;
- передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

6. Після завершення циклу ще раз отримайте прогноз моделі.
7. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:
   - 0 — дощу не буде;
   - 1 — дощ буде.

**Виведіть:**
- ймовірності, отримані від моделі;
- прогнози моделі (0 або 1);
- правильні відповіді;
- значення функції втрат.
